# Generated by Django 5.2.6 on 2025-10-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='report_images/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('robo', 'Robo'), ('asalto', 'Asalto'), ('vandalismo', 'Vandalismo'), ('iluminacion', 'Poca iluminación'), ('accidente', 'Accidente de Tránsito'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=10),
        ),
    ]
