# Generated by Django 5.2.6 on 2025-10-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_reporte_imagen_reporte_tipo_alter_reporte_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('muy_alto', 'Muy alto'), ('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('robo', 'Robo'), ('asalto', 'Asalto'), ('hurto', 'Hurto'), ('vandalismo', 'Vandalismo'), ('iluminacion', 'Poca iluminación'), ('accidente', 'Accidente de Tránsito'), ('violencia', 'Violencia'), ('consumo_drogas', 'Consumo/venta de drogas'), ('incendio', 'Incendio'), ('amenaza', 'Amenaza'), ('otro', 'Otro'), ('robo_vehiculo', 'Robo de vehículos'), ('acoso_callejero', 'Acoso callejero'), ('prostitucion_ilegal', 'Prostitución ilegal'), ('fraude_estafa', 'Fraudes y estafas')], default='otro', max_length=30),
        ),
    ]
